# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973d59da6c1f948205cde4024f79b69c24a85e1ec4d1873755bc9caa6a13cc0c071ee94d05d19c9ab566a4ff88efcdead71ae662954f47e380484463849b7678

test:
  secret_key_base: ef94032217a5b1dbf5003670fc4b4dbf24bbe4d16ee47e5d0406273b3e1383d847c2b2fb735ce08198f64a85471eef0745c72bc0cec2869416e52d247a9d6f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
